spring.datasource.url=jdbc:postgresql://localhost:5432/submit_and_review
spring.datasource.username=postgres
spring.datasource.password=mel09

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
